// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240717225509_CorrigiendoPKVilla")]
    partial class CorrigiendoPKVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Villa de lujo",
                            FechaActualizacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9621),
                            FechaCreacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9605),
                            ImagenUrl = "",
                            MetrosCuadrados = 200,
                            Nombre = "Villa 1",
                            Ocupantes = 4,
                            Tarifa = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Villa de lujo2",
                            FechaActualizacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9624),
                            FechaCreacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9624),
                            ImagenUrl = "",
                            MetrosCuadrados = 300,
                            Nombre = "Villa 2",
                            Ocupantes = 5,
                            Tarifa = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "",
                            Detalle = "Villa de luj3o",
                            FechaActualizacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9627),
                            FechaCreacion = new DateTime(2024, 7, 17, 16, 55, 9, 108, DateTimeKind.Local).AddTicks(9627),
                            ImagenUrl = "",
                            MetrosCuadrados = 400,
                            Nombre = "Villa 3",
                            Ocupantes = 6,
                            Tarifa = 3000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
